# Generated by Django 5.2.1 on 2025-07-17 00:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_producto_registro_delete_blog_delete_buscar_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='usuario_creador',
            field=models.ForeignKey(default=0.0, on_delete=django.db.models.deletion.CASCADE, related_name='productos_subidos', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
